<?php
session_start();

if (!isset($_SESSION['username'])) {
    header("Location: login.php");
    exit();
}


//database information variables
$servername = "task2-db-1";
$username = "root";
$password = "csym019";
$dbname = "csym019_database";

try {
    $conn = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password);
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $e) {
    die("Connection failed: " . $e->getMessage());
}


//null columns
$columnNames = [
    "fees_uk_full_time",
    "fees_uk_part_time",
    "fees_uk_integrated_foundation_year",
    "fees_international_integrated_foundation_year",
    "fee_international_full",
    "fee_international_part",
    "fees_optional_work_placement_year"
];


function saveCourseData($conn, $courseName, $courseLevel, $iconFile, $overview, $highlights, $details, $req, $faqs, $modules, $feesTypes, $figures)
{
    try {
        $conn->beginTransaction();

        //prepare insert statement for course table and bind to values
        $sql = "INSERT INTO Course (title, `level`,iconPath, overview, highlights, course_details, entry_requirements, faq) VALUES (:course_name, :course_level,:iconPath, :overview, :highlights, :details, :req, :faq)";
        $stmt = $conn->prepare($sql);
        $stmt->bindParam(':course_name', $courseName, PDO::PARAM_STR);
        $stmt->bindParam(':course_level', $courseLevel);
        $stmt->bindParam(':overview', $overview);
        $stmt->bindParam(':highlights', $highlights);
        $stmt->bindParam(':iconPath', $iconFile);
        $stmt->bindParam(':details', $details);
        $stmt->bindParam(':req', $req);
        $stmt->bindParam(':faq', $faqs);
        $success = $stmt->execute();

        if (!$success) {
            throw new Exception("Failed to insert into Course table.");
        }

        $courseId = $conn->lastInsertId(); // get autogenerated id

        foreach ($modules as $module) { //iterate modules array input and parse int values of credits
            $moduleName = $module['name'];
            $moduleCredit = intval($module['credit']);

            //insert statement for modules tables with the course id
            $sql_module = "INSERT INTO Modules (module_name, credits, course_id) VALUES (:module_name, :credits, :course_id)";
            $stmt_module = $conn->prepare($sql_module);
            $stmt_module->bindParam(':module_name', $moduleName);
            $stmt_module->bindParam(':credits', $moduleCredit);
            $stmt_module->bindParam(':course_id', $courseId);
            $success1 = $stmt_module->execute();

            if (!$success1) {
                throw new Exception("Failed to insert into Modules table.");
            }
        }

        if (is_array($feesTypes)) {
            for ($i = 0; $i < count($feesTypes); $i++) {
                $feesType = $feesTypes[$i];
                $figure = $figures[$i];

                //input fees based on select options for fee columns
                $sql_fees = "UPDATE Course SET $feesType = :figure WHERE course_id = :courseId";
                $stmt_fees = $conn->prepare($sql_fees);
                $stmt_fees->bindParam(':figure', $figure);
                $stmt_fees->bindParam(':courseId', $courseId);
                $stmt_fees->execute();

                if (!$stmt_fees) {
                    throw new Exception("Failed to update Course table with fees.");
                }
            }
        }

        $conn->commit();
    } catch (PDOException $e) {
        $conn->rollBack();
        echo "Error: " . $e->getMessage();
        exit();
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') { //when form submit post  get user inputs
    $courseName = $_POST['course_name'];
    $courseLevel = $_POST['course_level'];
    $overview = $_POST['overview'];
    $highlights = $_POST['highlights'];
    $details = $_POST['details'];
    $req = $_POST['req'];
    $feesTypes = $_POST['feesType'];
    $figures = $_POST['figure'];
    $faqs = $_POST['faqss'];
    $modules = array();

    if (isset($_POST['module']) && isset($_POST['credit'])) { //checks for as many modules entered by user
        $moduleNames = $_POST['module'];
        $moduleCredits = $_POST['credit'];

        for ($i = 0; $i < count($moduleNames); $i++) { //maps the names and objects to array
            $moduleName = $moduleNames[$i];
            $moduleCredit = $moduleCredits[$i];
            $modules[] = array('name' => $moduleName, 'credit' => $moduleCredit);
        }
    }

    $file_name = "";
    if (isset($_FILES['course_icon'])) { //for file object, move it to storage and get name of file
        $file_name = $_FILES['course_icon']['name'];
        $file_tmp = $_FILES['course_icon']['tmp_name'];
        move_uploaded_file($file_tmp, $file_name);
    }

    //call save course method
    saveCourseData($conn, $courseName, $courseLevel, $file_name, $overview, $highlights, $details, $req, $faqs, $modules, $feesTypes, $figures);
}
?>



<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Course Report</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="addNewCourse.js"></script>
    <link rel="stylesheet" href="layout.css">
</head>

<body class="body">
    <header>
        <h3>CSYM019 - UNIVERSITY COURSES</h3>
    </header>
    <nav>
        <ul>
            <li><a href="./courseSelectionForm.php">Course Report</a></li>
            <li><a href="./newCourse.php">New Course</a></li>
        </ul>
    </nav>
    <main class="main">
        <h3>Sample New Course Entry Form</h3>
        <div class="form-container">
            <form action="newCourse.php" method="POST" enctype="multipart/form-data">
                <div class="inner-form">
                    <div>
                        <label for="course_name">Course Name:</label>
                        <input type="text" name="course_name" id="course_name" required />
                    </div>
                    <div>
                        <label for="course_level">Level:</label>
                        <input type="text" name="course_level" id="course_level" required />
                    </div>
                    <div>
                        <label for="course_icon">Icon:</label>
                        <input type="file" name="course_icon" id="course_icon" required />
                    </div>
                    <div>
                        <label for="overview">Overview</label>
                        <textarea rows="4" cols="40" name="overview" id="overview" required></textarea>
                    </div>
                    <div>
                        <label for="highlights">Highlights</label>
                        <textarea rows="4" cols="40" name="highlights" id="highlights" required></textarea>
                    </div>
                    <div>
                        <label for="details">Course Details</label>
                        <textarea rows="4" cols="40" name="details" id="details" required></textarea>
                    </div>
                    <div>
                        <label for="req">Entry Requirements</label>
                        <textarea rows="4" cols="40" name="req" id="req" required></textarea>
                    </div>
                    <section>
                        <div id="modulesContainer">
                            <div class="module-input">
                                <input type="text" name="module[]" placeholder="Module Name">
                                <input type="text" name="credit[]" placeholder="Credit" pattern="[0-9]+" title="Please enter a number">
                            </div>
                        </div>
                        <button id="addModuleButton" type="button">Add Module</button>
                    </section>
                    <section>
                        <div id="feesContainer">
                            <div class="fee-input">
                                <select name="feesType[]" id="mySelect" title="mySelect">
                                    <option value="fees_uk_full_time">Uk Full Time</option>
                                    <option value="fees_uk_part_time">Uk part time</option>
                                    <option value="fees_uk_integrated_foundation_year">Uk foundation</option>
                                    <option value="fees_international_integrated_foundation_year">International Full time</option>
                                    <option value="fee_international_full">International Part time</option>
                                    <option value="fee_international_part">International Foundation</option>
                                    <option value="fees_optional_work_placement_year">Work Placement</option>
                                </select>
                                <input type="text" name="figure[]" placeholder="Figure" pattern="[0-9]+" title="Please enter a number">
                            </div>
                        </div>
                        <button id="addFeeButton" type="button">Add Fee</button>
                    </section>

                    <div>
                        <label for="faqss">FAQs</label>
                        <textarea rows="4" cols="40" name="faqss" id="faqss" required></textarea>
                    </div>

                    <input type="submit" value="Add Course" />
                    <!--input type="reset" value="Cancel" /-->
                </div>
            </form>
        </div>
    </main>
    <footer>&copy; CSYM019 2023</footer>

</body>

</html>